# Generated by Django 4.1.3 on 2022-12-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_subject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=30, verbose_name='Имя заявителя')),
                ('applicant_surname', models.CharField(max_length=30, verbose_name='Фамилия заявителя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.application')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.status')),
            ],
            options={
                'verbose_name': 'Установленный статус заявки',
                'verbose_name_plural': 'Установленные статусы заявок',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='statuses',
            field=models.ManyToManyField(related_name='applications', through='education.ApplicationStatus', to='education.status'),
        ),
        migrations.AddField(
            model_name='application',
            name='subjects',
            field=models.ManyToManyField(related_name='applications', to='education.subject'),
        ),
    ]
