# Generated by Django 4.1.3 on 2022-12-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_application_status_applicationstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Доступный статус заявки', 'verbose_name_plural': 'Доступные статусы заявок'},
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='note',
            field=models.CharField(blank=True, max_length=150, verbose_name='Примечание'),
        ),
    ]
