# Generated by Django 4.1.3 on 2022-12-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_status_options_applicationstatus_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
    ]
