# Generated by Django 4.1.3 on 2022-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='applications', to='education.subject'),
        ),
    ]
