# Generated by Django 4.1.3 on 2022-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_group_options_alter_group_subject_studentgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='created_at',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='enrolled_at',
            field=models.DateField(default='2022-05-05', verbose_name='Дата зачисления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='expelled_at',
            field=models.DateField(default='2022-05-05', verbose_name='Дата отчисления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Студент в группе'),
            preserve_default=False,
        ),
    ]
