# Generated by Django 4.1.3 on 2022-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_studentgroup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='enrolled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='expelled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отчисления'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Студент в группе'),
        ),
    ]
