# Generated by Django 4.1.3 on 2022-12-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_studentgroup_enrolled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('monday', 'Дүйсенбі'), ('tuesday', 'Сейсенбі'), ('wednesday', 'Сәрсенбі'), ('thursday', 'Бейсенбі'), ('friday', 'Жұма'), ('saturday', 'Сенбі')], max_length=15, verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Время начала занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedules', to='education.group')),
            ],
        ),
    ]
