# Generated by Django 4.1.3 on 2022-12-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_shedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
